### ISSUE TITLE
大佬好，安装完catalina之后设置界面里没有蓝牙选项

### ISSUE THREAD

**Issue by kanji003** [matri/hipda-h170-opencore#1]
无线功能正常，蓝牙在系统偏好设置里找不到，请帮忙查看是哪里问题

**Comment by matri** [comment]
你得把环境说一下，什么网卡，型号，然后把efi打包发上来吧。

**Comment by kanji003** [comment]
不好意思大佬，是我自己的问题，把1820A的网卡卸下来重新安装就好了，非常完美，多谢了
